#!/bin/sh
# --------------------------------------------------------------
# SPDX-License-Identifier: GPL-3.0-or-later
# --------------------------------------------------------------
# deb File      : postinst
# File Authors  : sanchuanhehe <wyihe5520@gmail.com>
# Contributors  :   Nil Null   <nil@null.org>
#	            |
# Created On    : <2025-06-14>
# Last Modified : <2025-06-16>
#
# postinst script for chsrc
# --------------------------------------------------------------

set -e

case "$1" in
    configure)
        # Update man database
        if command -v mandb >/dev/null 2>&1; then
            mandb -q /usr/share/man/man1/chsrc.1 2>/dev/null || true
        fi

        # Make sure chsrc is executable
        chmod +x /usr/bin/chsrc

        echo "chsrc has been successfully installed!"
        echo "Run 'chsrc help' to get started."
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
