#!/bin/sh
# --------------------------------------------------------------
# SPDX-License-Identifier: GPL-3.0-or-later
# --------------------------------------------------------------
# DEB File      : prerm
# File Authors  : sanchuanhehe <wyihe5520@gmail.com>
# Contributors  :   Nil Null   <nil@null.org>
#	            |
# Created On    : <2025-06-14>
# Last Modified : <2025-06-15>
#
# prerm script for chsrc
# --------------------------------------------------------------

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Nothing special to do during removal
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
